name: build-portDNN
description: Action to clone and build portDNN using oneAPI

inputs:
  workspace:
    description: 'Main workflow workspace'
    default: ${{ github.workspace }}

runs:
  # We don't want a new docker just a list of steps, so mark as composite
  using: "composite"
  steps:
    - name: Clone portDNN
      shell: bash
      run: git clone --recursive https://github.com/codeplaysoftware/portDNN.git

    - name: Set up Environment and build portDNN
      shell: bash
      run: |
        ls
        export LD_LIBRARY_PATH=${{ inputs.workspace }}/linux_nightly_release/lib:$LD_LIBRARY_PATH
        export CMAKE_CXX_COMPILER=${{ inputs.workspace }}/linux_nightly_release/bin/clang++
        export CMAKE_C_COMPILER=${{ inputs.workspace }}/linux_nightly_release/bin/clang
        export OCL_ICD_FILENAMES=${{ inputs.workspace }}/install/lib/libCL.so

        cmake -B portDNN_build_dir portDNN -GNinja -DCMAKE_INSTALL_PREFIX=portDNN_install_dir -DCMAKE_CXX_COMPILER=$(pwd)/linux_nightly_release/bin/clang++ -DSNN_BUILD_BENCHMARKS=OFF -DSNN_BENCH_SYCLBLAS=OFF -DSNN_BUILD_DOCUMENTATION=OFF
        ninja -C portDNN_build_dir install